### PR TITLE
allow DriverManager to be extended by changing properties to protected

### PR DESCRIPTION
**Pull request by neklein**
@ctwillie would you be willing to allow the DriverManager properties to protected rather than private? That way I can create my own DriverManager that extends yours and also create additional drivers for personal use.

### CODE REVIEW

**Comment by ctwillie** [comment]
@neklein I've been thinking if this is the best approach to allowing other drivers. I feel this approach would invite bug reports that do not have anything to do with the core code base, but the users implementation of the added driver. I am willing to collab on PR's to add new drivers if you have started any. Truthfully, just short on time right now.

Thoughts?

**Comment by neklein** [comment]
@ctwillie that makes sense - I do think with allowing the fields to be protected rather than private, you invite some collaboration.

Based on current usage, I'm not sure you would get bug reports - though I could be wrong. In my case, I created DriverManager that extends yours so that I could overwrite a few methods. I think someone who would do the work to figure out how to extend it also probably wouldn't need to submit a but report. That's my thought, anyway.

I did want to push my database driver and see if it would fit your system. Unfortunately, most of my PHP experience comes within the Laravel framework so I'm not sure about all the limitations of a pure PHP package.

Would you like me to add my DriverManager changes and DatabaseDriver to my fork and create a pull request? You could then take a look and see if it would be a simple thing to translate from the Laravel style to a purer PHP style.

**Comment by cedrictwillie** [comment]
I'd rather help implement the database driver than open the class to extension. Being the driver is what we are really after. So yes, let's start with your PR and go from there!

**Comment by neklein** [comment]
@cedrictwillie that makes sense. I'm working on a more detailed pull request - switching some stuff from Laravel to straight php. Hopefully I'll have something for you by the end of this week!

**Pull request closed without merging**
