### PR TITLE
Feature/add db driver

### PR DESCRIPTION
**Pull request by neklein**
@ctwillie Here is the start of my pull request. It still obviously needs a lot of work and I haven't added any testing yet, but feel free to look and offer feedback.

### CODE REVIEW

**Comment by neklein** [comment]
@ctwillie A question related to DB tables in vanilla PHP - how would you go about validating that a table exists? Stackoverflow had a couple of suggestions (that I forgot to save), but I'm only in Laravel, so I'm having trouble assessing for vanilla PHP.

**Comment by bradjones1** [comment]
I think this is an interesting idea but honestly this strikes me as domain bloat; if you need to integrate with a database layer, then you can easily build an adapter that doesn't need to live in this package, and interface with it.

**Comment by neklein** [comment]
@bradjones1 that may well be true, but right now the package is only willing to save data to a file, so users have to do extensive building to get a workaround.

My hope is simply to open the package up to a willingness to save the data to the database. If there is a way to simplify this and add less logic, I'm all for it.

**Comment by bradjones1** [comment]
> but right now the package is only willing to save data to a file, so users have to do extensive building to get a workaround.

Right, and I think that's probably too much, too. I'm not the maintainer or original author of the package but I think the more an SDK focuses on its domain, and defers other concerns to more specialized packages, the better. E.g. I am using this package inside of a Drupal project and Drupal's ORM handles storing all the pertinent information.

**Comment by bradjones1** [comment]
Let's see if @ctwillie chimes in on either of these PRs... I may end up forking this and refactoring to be more my style under the [`@meet-kinksters`](https://github.com/meet-kinksters) namespace, anyway.

**Comment by ctwillie** [comment]
@neklein @bradjones1 I've been back and forth on the DB driver as well.

The file "driver" is only used for channel subscriptions. The only downside to not having a "database driver" is you lose all subscriptions if the internal file is removed (deployments, dependency updates, etc). But to @bradjones1's point, storing user/channel subscriptions does seem to be the devs responsibility. It seems odd to have a database table that "you can't touch", and is reserved for a package.

So maybe we hold off on the database driver feature. User can store subscriptions in the database themselves, loop and send to users. Thoughts?

**Comment by cedrictwillie** [comment]
Ok, sounds good. Thank you for your contributions!

**Pull request closed without merging**
